Feature/#219-retrieve-profile-student-image
IT-Academy-BCN/ita-profiles pull request #230
Opened 2024-07-27 09:34 UTC by diegdar

Get the url student image profile with the endpoint:
GET->student/{studentId}/resume/photo

2024-07-29 09:02 UTC, ivanlegranbizarro approved these changes

2024-07-29 09:02 UTC, JustTheDude001 commented
Why .env.docker empty file? I am trying to test the app but some confing parameters are missing. 
![image](https://github.com/user-attachments/assets/aa7f4139-6cde-4800-a746-36f9625090e0)
I think it is due the .env.docker file being empty.

2024-07-29 10:48 UTC, jordimorillo requested changes
Fix your branch and remove the commits not belonging to you

2024-07-29 10:48 UTC, jordimorillo commented on app/Http/Requests/UpdateImageStudentRequest.php
> +
declare(strict_types=1);

2024-07-30 10:29 UTC, jordimorillo approved these changes
Well done!

2024-07-30 11:28 UTC, merged