246 refactor make a pivot table between resumes and additional trainings
IT-Academy-BCN/ita-profiles pull request #257
Opened 2024-09-23 09:56 UTC by begoIT24

We have created a pivot table between resumes and collaborations instead of the additional_trainings column, and have adjusted the model, service, and testing in concordance.
All functionalities are working well.

2024-09-23 10:51 UTC, jordimorillo requested changes
Review comments

2024-09-23 10:51 UTC, jordimorillo commented on database/factories/ResumeFactory.php
> +           // 'additional_trainings_ids' => json_encode($additionalTrainingsIds),
Delete, never comment

2024-09-23 10:51 UTC, jordimorillo commented on tests/Fixtures/Resumes.php
Ojo no te cargues las relaciones de los fixtures. Habla con Stephane.

2024-09-23 10:51 UTC, jordimorillo commented on app/Models/Resume.php
> +        return $this->belongsToMany(AdditionalTraining::class, 'additional_training_resume', 'resume_id', 'additional_training_id');
Comenta con Stephane como lo ha hecho para dejar esto mas limpio

2024-09-24 20:44 UTC, begoIT24 commented on database/factories/ResumeFactory.php
> +           // 'additional_trainings_ids' => json_encode($additionalTrainingsIds),
Done

2024-09-24 20:45 UTC, begoIT24 commented on tests/Fixtures/Resumes.php
Aclarado

2024-09-25 06:55 UTC, begoIT24 commented on app/Models/Resume.php
> +        return $this->belongsToMany(AdditionalTraining::class, 'additional_training_resume', 'resume_id', 'additional_training_id');
Simplificado siguiendo convención de nombres de Laravel

2024-09-25 10:05 UTC, jordimorillo commented on app/Models/AdditionalTraining.php
/**
 * @see https://laravel.com/docs/10.x/eloquent-relationships#many-to-many
 */

2024-09-25 10:12 UTC, jordimorillo commented on app/Models/AdditionalTraining.php
> +         // As a guide, we implement Laravel naming conventions for relationships.
Remove this comments

2024-09-25 10:14 UTC, jordimorillo approved these changes
Well done!

2024-09-25 10:14 UTC, nachoa88 approved these changes

2024-09-25 10:17 UTC, begoIT24 commented on app/Models/AdditionalTraining.php
> +         // As a guide, we implement Laravel naming conventions for relationships.
done

2024-09-25 10:17 UTC, merged