Refactor taglist
IT-Academy-BCN/ita-profiles pull request #356
Opened 2024-10-30 09:01 UTC by GabrielCLuque

2024-10-31 09:26 UTC, ivanlegranbizarro requested changes

2024-10-31 09:26 UTC, ivanlegranbizarro commented on app/Http/Controllers/api/Tag/TagListController.php
> +
No es que el código esté mal de por sí, pero por seguir las convenciones, aquí sería mejor un TagCollection. Si vas a presentar 1 solo recurso está bien hacer un Resource, pero si vas a presentar un conjunto de recursos es mejor una Collection. Además, aunque tu Controller está bien y es bastante limpio, si haces una Collection te ahorrarás hacer un mapeo en mitad del controlador.

2024-10-31 12:14 UTC, jordimorillo reviewed
Gabriel revisa lo que te dice Iván. Su propuesta tiene muy buena pinta de ser un buen refactor. Por otro lado, éste controller tiene test?

2024-11-04 11:04 UTC, jordimorillo approved these changes

2024-11-07 10:09 UTC, StephaneCarteaux approved these changes

2024-11-07 10:11 UTC, ivanlegranbizarro approved these changes

2024-11-07 10:12 UTC, merged