430 fe create modal component
IT-Academy-BCN/ita-profiles pull request #441
Opened 2024-12-03 10:25 UTC by JuanDNJ

## Imagenes

### Modal.test.tsx
![image](https://github.com/user-attachments/assets/7fe606bd-de7b-4e6a-9a17-06104f327d97)

### Modal.tsx
![image](https://github.com/user-attachments/assets/d95fd134-476b-4995-b8c4-f6e42622352c)

###  modal.module..css
![image](https://github.com/user-attachments/assets/4a51253b-a025-4847-862a-f6d18e42532f)

2024-12-03 13:47 UTC, kevinmamaqi requested changes

2024-12-03 13:47 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Modal.test.tsx
> +  // Se tiene que ver cuando esté abierto
```suggestion
```

2024-12-03 13:47 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Modal.test.tsx
> +  // No se debería ver cuando esté cerrado
```suggestion
```

2024-12-03 13:47 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Modal.test.tsx
> +  // Llama a onClose cuando se hace clic en la superposición
```suggestion
```

2024-12-03 13:47 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Modal.test.tsx
> +  test("It should not be visible when closed.", () => {
En este test faltaria un elemento de interacción que lo abra

2024-12-03 13:47 UTC, kevinmamaqi commented on src/components/atoms/modal/Modal.tsx
> +      <div role="button" tabIndex={0} onKeyDown={handleKeyDown} className={styleModal.content} onClick={(e) => e.stopPropagation()}>
Children no debería estar dentro de button, esta mal.

2024-12-03 13:47 UTC, kevinmamaqi commented on src/components/atoms/modal/css/modal.module.css
> +.overlay {
Si la aplicación se ha decidido usar tailwind, continuaria con tailwind.

2024-12-04 08:18 UTC, kevinmamaqi commented on src/components/atoms/modal/css/modal.module.css
> +.overlay {
hmmm... pensaba que tailwind iba directamente al html del omponente, no usaria css modules en absoluto.

2024-12-04 09:58 UTC, JuanDNJ commented on src/__tests__/components/atoms/Modal.test.tsx
> +  test("It should not be visible when closed.", () => {
He cambiado los test, con más casos de uso, a ver que te parece. Espero que sea a mejor ...

2024-12-04 10:34 UTC, kevinmamaqi reviewed
Faltaria un test en el que se abre el modal y aparece el contenido.

2024-12-04 10:34 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Modal.test.tsx
> +  test("should by defined", () => {
Eliminar este test, es redundante.

2024-12-04 10:34 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Modal.test.tsx
> +  test("should call onClose when Enter key is pressed on modal-content", () => {
Este comportamiento es erróneo, especialmente si hay un botón de submit. Debería cerrarse al presionar `esc` no enter

2024-12-04 10:34 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Modal.test.tsx
> +  test("should call onClose when Space key is pressed on modal-content", () => {
Lo mismo.

2024-12-04 10:34 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Modal.test.tsx
> +  test("should not call onClose when Enter key is pressed on overlay", () => {
Innecesario

2024-12-05 06:59 UTC, JuanDNJ commented
> Faltaria un test en el que se abre el modal y aparece el contenido.

Ya he creado el test, para verificar que se abre y cierra el modal.

2024-12-10 09:44 UTC, aida-rodi approved these changes

2024-12-12 08:51 UTC, olga1k approved these changes

2024-12-12 09:08 UTC, JuanDNJ reviewed
Espero aver resulto los cambios sugeridos

2024-12-12 21:47 UTC, kevinmamaqi approved these changes

2024-12-13 08:23 UTC, merged