427 create card component
IT-Academy-BCN/ita-profiles pull request #461
Opened 2024-12-10 17:01 UTC by aida-rodi

2024-12-11 07:01 UTC, kevinmamaqi requested changes

2024-12-11 07:01 UTC, kevinmamaqi commented on src/components/atoms/Card.tsx
> +    className={styles}
Utiliza classnames (de npm) y classname como prop para pasar estilos, no styles. Esos styles que pasas de esa manera deberían de sobreescribir los estilos base.

2024-12-11 07:01 UTC, kevinmamaqi commented on types.ts
> +export type TCard = {
Moverlo al componente, no debería de tener role

2024-12-11 07:01 UTC, kevinmamaqi commented on types.ts
> +export type TCard = {
Además los props deberían ser los mismos que tiene un div, `React.HTMLAttributes<HTMLDivElement>`

2024-12-11 07:02 UTC, kevinmamaqi commented on src/__tests__/components/atoms/Card.test.tsx
> +      styles={defaultCardStyles}>
Fijate en el button

2024-12-11 08:21 UTC, aida-rodi commented on types.ts
> +export type TCard = {
En ocasiones este elemento card puede necesitar un onClick, como es el caso de las tarjetas de candidato:

![image](https://github.com/user-attachments/assets/6ec2cd4e-a5df-4dae-a0fa-f3f2e3b3f4d0)

En el momento en que la card tiene un onClick siendo un elemento `<div>` salta un error de lint que pide que el componente tenga un rol: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/7566e13531f09a040daee4c16d0cba0c28d321c4/docs/rules/no-static-element-interactions.md

Es por esto que lo añadí, pero entiendo que hay una forma más correcta de resolver este caso. ¿Cuál sería @kevinmamaqi ?

2024-12-11 20:02 UTC, JuanDNJ commented
Me marca que da fallo el check.
![image](https://github.com/user-attachments/assets/b45877d8-68a2-457e-b24e-22367dea209c)

2024-12-12 13:40 UTC, olga1k approved these changes

2024-12-12 13:40 UTC, olga1k commented
Well done!

2024-12-12 13:41 UTC, JuanDNJ approved these changes
🙌

2024-12-12 14:24 UTC, kevinmamaqi approved these changes

2024-12-12 14:26 UTC, merged