Simplified  specializationListController into collection to filter and present values. Also refactored tests
IT-Academy-BCN/ita-profiles pull request #470
Opened 2024-12-12 18:16 UTC by sergilopez04

2024-12-12 20:14 UTC, StephaneCarteaux commented
Hola Sergi,
Has probado el endpoint GET /specialization/list con tu refactor?

2024-12-13 17:53 UTC, StephaneCarteaux requested changes

2024-12-13 17:53 UTC, StephaneCarteaux commented on app/Http/Controllers/api/Student/SpecializationListController.php
> +        $specializations = $student->resume?->specialization ?? collect();
Aquí no se tiene que aplicar $student

2024-12-18 16:48 UTC, sergilopez04 commented on app/Http/Controllers/api/Student/SpecializationListController.php
> +        $specializations = $student->resume?->specialization ?? collect();
He hecho los cambios, si me das tu okay hago un merge! Gracias por la aclaración

2024-12-18 22:05 UTC, ivanlegranbizarro approved these changes

2024-12-18 22:09 UTC, Amanda457 approved these changes

2024-12-19 07:49 UTC, StephaneCarteaux approved these changes

2024-12-19 08:05 UTC, merged